#url: http://localhost
baseurl: ''

# Site settings
title: Uachtar
email: oneillsinead20@gmail.com
description: "Home baked treats for any occasion or event also available at Carlow Farmers Market every Saturday 9am-2pm. Based in Kilkenny/Carlow"


# Team names, titles and social links
people:
- name: Sinead O'Neill
  pic: 1
  position: Lead Sweet-Things Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: https://instagram.com/uachtar_


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: instagram
    url: https://instagram.com/uachtar_


# Postal address (add as many lines as necessary)
address:
  - line: Carlow Farmer's Market
  - line: Kilkenny City 

# Build settings
markdown: kramdown
permalink: pretty